%% a_lfm_matched_filter_demo.m
% Step 6B: Explicit LFM matched filtering and pulse compression
%
% This standalone experiment demonstrates:
%
% noisy received LFM chirp
%       
% matched filtering
%      
% compressed range peak
%

clear;
clc;
close all;

rng(6, "twister");

%% Output folder

outputDir = "outputs_step6";

if ~isfolder(outputDir)
    mkdir(outputDir);
end

%% Radar and waveform parameters

c = 3e8;

sampleRateHz = 20e6;
chirpBandwidthHz = 20e6;
pulseDurationS = 10e-6;

chirpRateHzPerS = ...
    chirpBandwidthHz / pulseDurationS;

numPulseSamples = round( ...
    pulseDurationS * sampleRateHz);

pulseTimeS = ...
    (0:numPulseSamples - 1).' / sampleRateHz;

%% Generate complex baseband LFM waveform

instantaneousStartFrequencyHz = ...
    -chirpBandwidthHz / 2;

transmitChirp = exp( ...
    1j * 2*pi * ...
    ( ...
        instantaneousStartFrequencyHz * pulseTimeS + ...
        0.5 * chirpRateHzPerS * pulseTimeS.^2 ...
    ));

%% Simulated target

trueTargetRangeM = 300;

roundTripDelayS = ...
    2 * trueTargetRangeM / c;

delaySamples = round( ...
    roundTripDelayS * sampleRateHz);

echoAmplitude = 1;

%% Receive-record length

recordDurationS = 50e-6;

numRecordSamples = round( ...
    recordDurationS * sampleRateHz);

receivedClean = complex( ...
    zeros(numRecordSamples, 1));

echoStartIndex = delaySamples + 1;

echoStopIndex = ...
    echoStartIndex + numPulseSamples - 1;

receivedClean( ...
    echoStartIndex:echoStopIndex) = ...
    echoAmplitude * transmitChirp;

%% Add complex thermal noise

desiredInputSnrDb = -12;

noisePower = ...
    echoAmplitude^2 / ...
    10^(desiredInputSnrDb / 10);

noise = sqrt(noisePower / 2) * ...
    ( ...
        randn(numRecordSamples, 1) + ...
        1j * randn(numRecordSamples, 1) ...
    );

receivedSignal = receivedClean + noise;

%% Construct matched filter

matchedFilterCoefficients = ...
    conj(flipud(transmitChirp));

%% Apply matched filter

matchedOutput = conv( ...
    receivedSignal, ...
    matchedFilterCoefficients, ...
    "full");

matchedCleanOutput = conv( ...
    receivedClean, ...
    matchedFilterCoefficients, ...
    "full");

matchedNoiseOutput = conv( ...
    noise, ...
    matchedFilterCoefficients, ...
    "full");

%% Search valid delay hypotheses

validMatchedIndices = ...
    numPulseSamples:numRecordSamples;

validMatchedPower = ...
    abs(matchedOutput(validMatchedIndices)).^2;

[~, localPeakIndex] = max( ...
    validMatchedPower);

detectedPeakIndex = ...
    validMatchedIndices(localPeakIndex);

estimatedDelaySamples = ...
    detectedPeakIndex - numPulseSamples;

estimatedDelayS = ...
    estimatedDelaySamples / sampleRateHz;

estimatedTargetRangeM = ...
    estimatedDelayS * c / 2;

%% Measure input SNR

echoIndices = ...
    echoStartIndex:echoStopIndex;

measuredInputSnrDb = 10*log10( ...
    mean(abs(receivedClean(echoIndices)).^2) / ...
    mean(abs(noise(echoIndices)).^2));

%% Measure matched-filter output SNR

[~, trueCleanPeakIndex] = max( ...
    abs(matchedCleanOutput).^2);

matchedSignalPeakPower = ...
    abs(matchedCleanOutput(trueCleanPeakIndex)).^2;

matchedNoisePower = mean( ...
    abs( ...
        matchedNoiseOutput(validMatchedIndices) ...
    ).^2);

measuredOutputSnrDb = 10*log10( ...
    matchedSignalPeakPower / ...
    matchedNoisePower);

measuredProcessingGainDb = ...
    measuredOutputSnrDb - measuredInputSnrDb;

%% Theoretical pulse-compression quantities

timeBandwidthProduct = ...
    chirpBandwidthHz * pulseDurationS;

theoreticalProcessingGainDb = ...
    10*log10(timeBandwidthProduct);

rangeResolutionM = ...
    c / (2 * chirpBandwidthHz);

%% Print results

fprintf("Step 6B: LFM Matched Filtering\n");
fprintf("----------------------------------------\n");

fprintf("Pulse bandwidth:              %.1f MHz\n", ...
    chirpBandwidthHz / 1e6);

fprintf("Pulse duration:               %.1f us\n", ...
    pulseDurationS * 1e6);

fprintf("Time-bandwidth product:       %.1f\n", ...
    timeBandwidthProduct);

fprintf("Theoretical processing gain:  %.2f dB\n", ...
    theoreticalProcessingGainDb);

fprintf("Measured input SNR:           %.2f dB\n", ...
    measuredInputSnrDb);

fprintf("Measured output SNR:          %.2f dB\n", ...
    measuredOutputSnrDb);

fprintf("Measured SNR improvement:     %.2f dB\n", ...
    measuredProcessingGainDb);

fprintf("Range resolution:             %.2f m\n", ...
    rangeResolutionM);

fprintf("True target range:            %.2f m\n", ...
    trueTargetRangeM);

fprintf("Estimated target range:       %.2f m\n", ...
    estimatedTargetRangeM);

%% Create range axes

receivedRangeAxisM = ...
    (0:numRecordSamples - 1).' / ...
    sampleRateHz * c / 2;

matchedRangeAxisM = ...
    (validMatchedIndices - numPulseSamples).' / ...
    sampleRateHz * c / 2;

rawReceivedPowerDb = ...
    10*log10(abs(receivedSignal).^2 + eps);

normalizedMatchedPowerDb = ...
    10*log10( ...
        validMatchedPower / ...
        max(validMatchedPower) + eps);

%% Before and after figure

figure( ...
    "Color", ...
    "w", ...
    "Position", ...
    [100, 100, 1200, 850]);

layout = tiledlayout( ...
    2, ...
    1, ...
    "TileSpacing", ...
    "compact", ...
    "Padding", ...
    "compact");

%% Before matched filtering

ax1 = nexttile;

plot( ...
    receivedRangeAxisM, ...
    rawReceivedPowerDb, ...
    "LineWidth", ...
    1);

hold on;

xline( ...
    trueTargetRangeM, ...
    "--k", ...
    "True target delay", ...
    "LineWidth", ...
    1.5);

grid on;

xlim([0, 1000]);

ylabel("Received Power (dB)");

title(sprintf( ...
    "Before Matched Filtering: Noisy LFM Return, Input SNR = %.1f dB", ...
    measuredInputSnrDb));

ax1.Toolbar.Visible = "off";

%% After matched filtering

ax2 = nexttile;

plot( ...
    matchedRangeAxisM, ...
    normalizedMatchedPowerDb, ...
    "LineWidth", ...
    1.5);

hold on;

xline( ...
    trueTargetRangeM, ...
    "--k", ...
    "True range", ...
    "LineWidth", ...
    1.5);

plot( ...
    estimatedTargetRangeM, ...
    normalizedMatchedPowerDb(localPeakIndex), ...
    "ro", ...
    "MarkerSize", ...
    8, ...
    "LineWidth", ...
    1.5);

grid on;

xlim([0, 1000]);
ylim([-50, 5]);

xlabel("Delay-Estimated Range (m)");
ylabel("Normalized Power (dB)");

title(sprintf( ...
    "After Matched Filtering: Compressed Peak, Output SNR = %.1f dB", ...
    measuredOutputSnrDb));

legend( ...
    "Matched-filter output", ...
    "True target range", ...
    "Detected peak", ...
    "Location", ...
    "southwest");

ax2.Toolbar.Visible = "off";

title( ...
    layout, ...
    "LFM Pulse Compression: Before and After Matched Filtering");

%% Save figure

figureFile = fullfile( ...
    outputDir, ...
    "step6b_lfm_matched_filter_before_after.png");

exportgraphics( ...
    gcf, ...
    figureFile, ...
    "Resolution", ...
    300);

fprintf("\nSaved:\n");
fprintf("%s\n", figureFile);