%% b_generate_physics_based_fmcw_data.m
% Step 6C: Generate physics-based FMCW IQ data
%
% Received target power is calculated using the monostatic radar equation.
% Receiver noise is calculated using the thermal-noise equation.
%
% Creates 10 controlled scenarios near the radar's sensitivity limit.

clear;
clc;
close all;

rng(36, "twister");

%% Round 3 output folders

dataDir = "data_round3";
figDir  = "figures_round3";

if ~isfolder(dataDir)
    mkdir(dataDir);
end

if ~isfolder(figDir)
    mkdir(figDir);
end

%% FMCW radar parameters

params.c = 3e8;
params.fc = 10e9;
params.lambda = params.c / params.fc;

params.B = 20e6;
params.Tchirp = 50e-6;
params.S = params.B / params.Tchirp;

params.Nfast = 512;
params.Nchirps = 256;
params.fs = params.Nfast / params.Tchirp;
params.PRF = 1 / params.Tchirp;

params.range_res_m = params.c / (2 * params.B);

params.max_range_m = ...
    (params.fs / 2) * params.c / (2 * params.S);

params.max_unambiguous_velocity_mps = ...
    params.lambda / (4 * params.Tchirp);

%% Radar hardware assumptions

params.transmitPowerW = 0.1;        % 100 mW

params.txGainDb = 18;
params.rxGainDb = 18;

params.txGainLinear = ...
    10^(params.txGainDb / 10);

params.rxGainLinear = ...
    10^(params.rxGainDb / 10);

params.systemLossDb = 6;

params.systemLossLinear = ...
    10^(params.systemLossDb / 10);

%% Receiver thermal-noise model

params.boltzmann = 1.380649e-23;
params.temperatureK = 290;

params.noiseBandwidthHz = 20e6;

params.noiseFigureDb = 5;

params.noiseFactorLinear = ...
    10^(params.noiseFigureDb / 10);

params.noisePowerW = ...
    params.boltzmann * ...
    params.temperatureK * ...
    params.noiseBandwidthHz * ...
    params.noiseFactorLinear;

params.noisePowerDbm = ...
    10*log10(params.noisePowerW / 1e-3);

%% Display radar configuration

fprintf("Step 6C: Physics-Based FMCW IQ Generator\n");
fprintf("----------------------------------------\n");

fprintf("Carrier frequency:                 %.2f GHz\n", ...
    params.fc / 1e9);

fprintf("Bandwidth:                         %.2f MHz\n", ...
    params.B / 1e6);

fprintf("Range resolution:                  %.2f m\n", ...
    params.range_res_m);

fprintf("Maximum unambiguous velocity:      %.1f m/s\n", ...
    params.max_unambiguous_velocity_mps);

fprintf("Transmit power:                    %.1f dBm\n", ...
    10*log10(params.transmitPowerW / 1e-3));

fprintf("Transmit/receive antenna gain:     %.1f/%.1f dBi\n", ...
    params.txGainDb, ...
    params.rxGainDb);

fprintf("System loss:                       %.1f dB\n", ...
    params.systemLossDb);

fprintf("Receiver thermal-noise power:      %.2f dBm\n\n", ...
    params.noisePowerDbm);

%% Controlled stress scenarios
%
% Each class includes targets near the 0 dB input-SNR crossing found
% during Step 6A.

scenarioClasses = [ ...
    "DOG"; ...
    "DOG"; ...
    "DOG"; ...
    "HUMAN"; ...
    "HUMAN"; ...
    "HUMAN"; ...
    "CAR"; ...
    "CAR"; ...
    "PLANE"; ...
    "PLANE" ...
];

scenarioRangesM = [ ...
     50; ...
     65; ...
     80; ...
     90; ...
    115; ...
    140; ...
    170; ...
    220; ...
    300; ...
    420 ...
];

scenarioVelocitiesMps = [ ...
      5.5; ...
     -7.0; ...
      4.5; ...
     -2.5; ...
      3.0; ...
     -2.8; ...
     18.0; ...
    -30.0; ...
     85.0; ...
   -120.0 ...
];

numScenarios = numel(scenarioClasses);

truthRows = table();

%% Generate Round 3 scenarios

for scenarioID = 1:numScenarios

    target = make_controlled_target( ...
        scenarioClasses(scenarioID), ...
        scenarioRangesM(scenarioID), ...
        scenarioVelocitiesMps(scenarioID));

    %% Assign class-dependent RCS

    target.rcs_m2 = get_class_rcs(target.class);

    %% Calculate physical received power

    target.received_power_w = ...
        calculate_received_power( ...
            target.range_m, ...
            target.rcs_m2, ...
            params);

    target.received_power_dbm = ...
        10*log10(target.received_power_w / 1e-3);

    target.input_snr_db = ...
        10*log10( ...
            target.received_power_w / ...
            params.noisePowerW);

    % Complex-signal amplitude whose mean power is received_power_w
    target.amplitude = ...
        sqrt(target.received_power_w);

    %% Generate IQ data

    addClutter = true;

    [iq, scene] = generate_fmcw_iq( ...
        target, ...
        params, ...
        addClutter);

    %% Save IQ scenario

    filename = sprintf( ...
        "raw_iq_scenario_%03d.mat", ...
        scenarioID);

    save( ...
        fullfile(dataDir, filename), ...
        "iq", ...
        "scene", ...
        "params");

    %% Add scenario to truth table

    newRow = table( ...
        scenarioID, ...
        string(filename), ...
        string(target.class), ...
        target.range_m, ...
        target.velocity_mps, ...
        abs(target.velocity_mps), ...
        target.rcs_m2, ...
        target.received_power_dbm, ...
        params.noisePowerDbm, ...
        target.input_snr_db, ...
        target.micro_doppler_spread_mps, ...
        target.motion_variation_code, ...
        'VariableNames', { ...
            'scenario_id', ...
            'raw_iq_file', ...
            'target_class', ...
            'range_m', ...
            'radial_velocity_mps', ...
            'speed_mps', ...
            'rcs_m2', ...
            'received_power_dbm', ...
            'noise_power_dbm', ...
            'input_snr_db', ...
            'micro_doppler_spread_mps', ...
            'motion_variation_code' ...
        });

    truthRows = [truthRows; newRow];

    fprintf( ...
        "Scenario %03d | %-5s | R = %6.1f m | " + ...
        "v = %+7.1f m/s | RCS = %6.2f m^2 | " + ...
        "Pr = %7.2f dBm | input SNR = %+6.2f dB\n", ...
        scenarioID, ...
        target.class, ...
        target.range_m, ...
        target.velocity_mps, ...
        target.rcs_m2, ...
        target.received_power_dbm, ...
        target.input_snr_db);

    %% Save preview for Scenario 001

    if scenarioID == 1

        make_preview_plot( ...
            iq, ...
            params, ...
            scene, ...
            fullfile( ...
                figDir, ...
                "scenario_001_physics_range_doppler_preview.png"));

    end
end

%% Save Round 3 truth table

truthFile = fullfile( ...
    dataDir, ...
    "truth_table.csv");

writetable(truthRows, truthFile);

fprintf("\nSaved %d physics-based IQ scenarios to:\n", ...
    numScenarios);

fprintf("%s\n", dataDir);
fprintf("\nSaved truth table:\n%s\n", truthFile);
fprintf("\nSaved preview figure to:\n%s\n", figDir);

%% ------------------------------------------------------------------------
% Local functions
% -------------------------------------------------------------------------

function target = make_controlled_target( ...
    targetClass, ...
    rangeM, ...
    velocityMps)

    target.class = char(targetClass);
    target.range_m = rangeM;
    target.velocity_mps = velocityMps;

    switch upper(target.class)

        case "DOG"

            target.micro_doppler_spread_mps = ...
                rand_uniform(2.0, 4.5);

            target.motion_variation_code = ...
                randi([7, 15]);

        case "HUMAN"

            target.micro_doppler_spread_mps = ...
                rand_uniform(0.8, 2.0);

            target.motion_variation_code = ...
                randi([3, 8]);

        case "CAR"

            target.micro_doppler_spread_mps = ...
                rand_uniform(0.2, 1.0);

            target.motion_variation_code = ...
                randi([0, 3]);

        case "PLANE"

            target.micro_doppler_spread_mps = ...
                rand_uniform(0.1, 0.8);

            target.motion_variation_code = ...
                randi([0, 3]);

        otherwise

            error( ...
                "Unsupported physical target class: %s", ...
                target.class);
    end
end

function rcsM2 = get_class_rcs(targetClass)

    switch upper(targetClass)

        case "DOG"
            rcsM2 = 0.1;

        case "HUMAN"
            rcsM2 = 1.0;

        case "CAR"
            rcsM2 = 10.0;

        case "PLANE"
            rcsM2 = 100.0;

        otherwise
            error("No RCS assumption exists for this class.");
    end
end

function receivedPowerW = calculate_received_power( ...
    rangeM, ...
    rcsM2, ...
    params)

    receivedPowerW = ...
        params.transmitPowerW * ...
        params.txGainLinear * ...
        params.rxGainLinear * ...
        params.lambda^2 * ...
        rcsM2 / ...
        ( ...
            (4*pi)^3 * ...
            rangeM^4 * ...
            params.systemLossLinear ...
        );
end

function [iq, scene] = generate_fmcw_iq( ...
    target, ...
    params, ...
    addClutter)

    Nfast = params.Nfast;
    Nchirps = params.Nchirps;

    tFast = (0:Nfast - 1).' / params.fs;
    tSlow = (0:Nchirps - 1) * params.Tchirp;

    iqTarget = complex(zeros(Nfast, Nchirps));

    %% Micro-Doppler target scatterers

    [velOffsets, relAmps] = ...
        make_micro_scatterers(target);

    % Normalize scatterer amplitudes so their total average power
    % approximately equals the radar-equation received power.
    relAmps = relAmps / norm(relAmps);

    for scattererIdx = 1:numel(velOffsets)

        scattererVelocity = ...
            target.velocity_mps + ...
            velOffsets(scattererIdx);

        scattererAmplitude = ...
            target.amplitude * ...
            relAmps(scattererIdx);

        initialPhase = 2*pi*rand();

        rangeAcrossChirpsM = ...
            target.range_m + ...
            target.velocity_mps * tSlow;

        rangeBeatFrequencyHz = ...
            2 * params.S * ...
            rangeAcrossChirpsM / ...
            params.c;

        dopplerFrequencyHz = ...
            2 * scattererVelocity / ...
            params.lambda;

        phase = ...
            2*pi * ...
            ( ...
                tFast * rangeBeatFrequencyHz + ...
                dopplerFrequencyHz * tSlow ...
            ) + ...
            initialPhase;

        iqTarget = ...
            iqTarget + ...
            scattererAmplitude * exp(1j * phase);
    end

    iq = iqTarget;

    %% Add stationary clutter using physical clutter RCS values

    clutterInfo = [];

    if addClutter

        numClutter = randi([3, 6]);

        for clutterIdx = 1:numClutter

            clutterRangeM = ...
                rand_uniform(15, 300);

            clutterRcsM2 = ...
                rand_uniform(0.005, 0.10);

            clutterPowerW = ...
                calculate_received_power( ...
                    clutterRangeM, ...
                    clutterRcsM2, ...
                    params);

            clutterAmplitude = ...
                sqrt(clutterPowerW);

            clutterPhase = ...
                2*pi*rand();

            clutterBeatFrequencyHz = ...
                2 * params.S * ...
                clutterRangeM / ...
                params.c;

            clutterSignal = ...
                clutterAmplitude * ...
                exp( ...
                    1j * ...
                    ( ...
                        2*pi * ...
                        tFast * ...
                        clutterBeatFrequencyHz + ...
                        clutterPhase ...
                    ));

            iq = ...
                iq + ...
                repmat( ...
                    clutterSignal, ...
                    1, ...
                    Nchirps);

            clutterInfo = [ ...
                clutterInfo; ...
                clutterRangeM, ...
                clutterRcsM2, ...
                10*log10(clutterPowerW / 1e-3) ...
            ];
        end
    end

    %% Add stationary receiver leakage

    leakagePowerW = ...
        params.noisePowerW * ...
        10^(10 / 10);

    leakageAmplitude = ...
        sqrt(leakagePowerW);

    iq = ...
        iq + ...
        leakageAmplitude * ...
        exp(1j * 2*pi*rand());

    %% Add complex thermal receiver noise

    noise = ...
        sqrt(params.noisePowerW / 2) * ...
        ( ...
            randn(size(iq)) + ...
            1j * randn(size(iq)) ...
        );

    iq = iq + noise;

    %% Save scene information

    scene.target = target;

    scene.receivedPowerW = ...
        target.received_power_w;

    scene.receivedPowerDbm = ...
        target.received_power_dbm;

    scene.noisePowerW = ...
        params.noisePowerW;

    scene.noisePowerDbm = ...
        params.noisePowerDbm;

    scene.inputSnrDb = ...
        target.input_snr_db;

    % Retain this field name for compatibility with older scripts.
    scene.snrDb = ...
        target.input_snr_db;

    scene.clutterInfo = ...
        clutterInfo;
end

function [velOffsets, relAmps] = ...
    make_micro_scatterers(target)

    spread = ...
        target.micro_doppler_spread_mps;

    switch upper(target.class)

        case "DOG"

            velOffsets = ...
                spread * ...
                [-0.80, -0.35, 0, 0.30, 0.75];

            relAmps = ...
                [0.20, 0.35, 1.00, 0.35, 0.20];

        case "HUMAN"

            velOffsets = ...
                spread * ...
                [-0.50, 0, 0.50];

            relAmps = ...
                [0.35, 1.00, 0.35];

        case "CAR"

            velOffsets = ...
                spread * ...
                [-0.25, 0, 0.25];

            relAmps = ...
                [0.20, 1.00, 0.20];

        case "PLANE"

            velOffsets = ...
                spread * ...
                [-0.15, 0, 0.15];

            relAmps = ...
                [0.15, 1.00, 0.15];

        otherwise

            velOffsets = 0;
            relAmps = 1;
    end
end

function make_preview_plot( ...
    iq, ...
    params, ...
    scene, ...
    outputFile)

    Nfast = params.Nfast;
    Nchirps = params.Nchirps;

    %% Apply first-order MTI for the preview

    iqMti = [ ...
        complex(zeros(Nfast, 1)), ...
        diff(iq, 1, 2) ...
    ];

    %% Hann window and 2D FFT

    rangeWin = local_hann(Nfast);
    dopplerWin = local_hann(Nchirps).';

    iqWindowed = ...
        iqMti .* ...
        rangeWin .* ...
        dopplerWin;

    rangeFFT = ...
        fft(iqWindowed, Nfast, 1);

    rdMap = ...
        fftshift( ...
            fft(rangeFFT, Nchirps, 2), ...
            2);

    %% Retain positive range bins

    halfIdx = ...
        1:floor(Nfast / 2);

    rdMapPositive = ...
        rdMap(halfIdx, :);

    magnitudeDb = ...
        20*log10(abs(rdMapPositive) + eps);

    magnitudeDb = ...
        magnitudeDb - max(magnitudeDb(:));

    %% Range and velocity axes

    beatFrequencyAxisHz = ...
        (halfIdx - 1) * ...
        params.fs / ...
        Nfast;

    rangeAxisM = ...
        beatFrequencyAxisHz * ...
        params.c / ...
        (2 * params.S);

    dopplerFrequencyAxisHz = ...
        (-Nchirps/2:Nchirps/2 - 1) * ...
        (params.PRF / Nchirps);

    velocityAxisMps = ...
        dopplerFrequencyAxisHz * ...
        params.lambda / 2;

    %% Plot

    figure( ...
        "Color", ...
        "w", ...
        "Position", ...
        [100, 100, 1100, 700]);

    imagesc( ...
        rangeAxisM, ...
        velocityAxisMps, ...
        magnitudeDb.');

    axis xy;
    colorbar;
    caxis([-45, 0]);

    xlabel("Range (m)");
    ylabel("Radial Velocity (m/s)");

    title(sprintf( ...
        "Physics-Based FMCW Preview | %s | " + ...
        "R = %.1f m | v = %+.1f m/s | Input SNR = %.1f dB", ...
        scene.target.class, ...
        scene.target.range_m, ...
        scene.target.velocity_mps, ...
        scene.inputSnrDb));

    grid on;

    gca.Toolbar.Visible = "off";

    exportgraphics( ...
        gcf, ...
        outputFile, ...
        "Resolution", ...
        200);
end

function w = local_hann(N)

    n = (0:N - 1).';

    w = ...
        0.5 - ...
        0.5*cos(2*pi*n / (N - 1));
end

function x = rand_uniform(a, b)

    x = ...
        a + ...
        (b - a)*rand();
end