%% Copyright © 2026 Sam Jensen. All rights reserved.

%% c_process_fmcw_detection_features.m
% Step 6D: Process physics-based FMCW scenarios
%
% Processing chain:
%   Raw physics-based IQ
%      -> MTI clutter removal
%      -> Hann windowing
%      -> Range-Doppler FFT
%      -> Edge-aware 2D CA-CFAR
%      -> Detection clustering
%      -> Strongest-cluster selection
%      -> Feature extraction and truth verification
%
% This Round 3 script is based on the working Step 5 feature extractor.
% It does not use truth range or velocity to gate or select detections.
% Truth is read only after detection to calculate estimation errors.

clear;
clc;
close all;

%% ------------------------------------------------------------------------
% folders
% -------------------------------------------------------------------------

dataDir = "data_round3";
outputDir = "outputs_round3";

if ~isfolder(outputDir)
    mkdir(outputDir);
end

%% ------------------------------------------------------------------------
% Find all physics-based radar scenarios
% -------------------------------------------------------------------------

rawFiles = dir(fullfile(dataDir, "raw_iq_scenario_*.mat"));

if isempty(rawFiles)
    error( ...
        "Step6D:NoFiles", ...
        "No raw IQ scenario files were found in data_round3.");
end

% Sort files so Scenario 001 comes before Scenario 002, etc.
[~, sortOrder] = sort({rawFiles.name});
rawFiles = rawFiles(sortOrder);

numScenarios = numel(rawFiles);

fprintf("Step 6D: Physics-Based FMCW Detection and Feature Extraction\n");
fprintf("------------------------------------------------------------\n");
fprintf("Number of scenarios found: %d\n", numScenarios);
fprintf("Detector selection uses no truth-centered range or velocity gate.\n\n");

%% ------------------------------------------------------------------------
% Preallocate physics, feature, and verification arrays
% -------------------------------------------------------------------------

scenario_id = zeros(numScenarios, 1);
actual_class = strings(numScenarios, 1);
detected = false(numScenarios, 1);

% Physics-based values used to describe the simulated input
received_power_dbm = nan(numScenarios, 1);
input_snr_db = nan(numScenarios, 1);
rcs_m2 = nan(numScenarios, 1);

% Truth values used only for verification after detection
truth_range_m = nan(numScenarios, 1);
truth_velocity_mps = nan(numScenarios, 1);

% Extracted radar features
estimated_range_m = nan(numScenarios, 1);
estimated_velocity_mps = nan(numScenarios, 1);
absolute_speed_mps = nan(numScenarios, 1);
peak_power_db = nan(numScenarios, 1);
estimated_snr_db = nan(numScenarios, 1);
cluster_cfar_cells = nan(numScenarios, 1);

% Detector diagnostics
total_cfar_cells = zeros(numScenarios, 1);
num_clusters = zeros(numScenarios, 1);

% Truth-verification errors
range_error_m = nan(numScenarios, 1);
velocity_error_mps = nan(numScenarios, 1);

%% ------------------------------------------------------------------------
% Process every scenario
% -------------------------------------------------------------------------

for fileIdx = 1:numScenarios

    %% Load current scenario

    rawFile = fullfile(dataDir, rawFiles(fileIdx).name);

    radarData = load(rawFile, "iq", "scene", "params");

    iq = radarData.iq;
    scene = radarData.scene;
    params = radarData.params;

    %% Read scenario number from filename

    scenarioToken = regexp( ...
        rawFiles(fileIdx).name, ...
        "(\d+)\.mat$", ...
        "tokens", ...
        "once");

    if isempty(scenarioToken)
        scenario_id(fileIdx) = fileIdx;
    else
        scenario_id(fileIdx) = str2double(scenarioToken{1});
    end

    %% Store physics and truth values

    actual_class(fileIdx) = string(scene.target.class);

    received_power_dbm(fileIdx) = scene.receivedPowerDbm;
    input_snr_db(fileIdx) = scene.inputSnrDb;
    rcs_m2(fileIdx) = scene.target.rcs_m2;

    truth_range_m(fileIdx) = scene.target.range_m;
    truth_velocity_mps(fileIdx) = scene.target.velocity_mps;

    %% Automatically derive CA-CFAR configuration
   

    desiredTrainingRange_m = 30;
    desiredGuardRange_m = 15;

    desiredTrainingVelocity_mps = 14;
    desiredGuardVelocity_mps = 5;

    rangeBinSize_m = ...
        params.c / (2 * params.B);

    velocityBinSize_mps = ...
        params.lambda * params.PRF / ...
        (2 * params.Nchirps);

    cfg.numTrainRange = max( ...
        1, ...
        round(desiredTrainingRange_m / rangeBinSize_m));

    cfg.numGuardRange = max( ...
        1, ...
        round(desiredGuardRange_m / rangeBinSize_m));

    cfg.numTrainDoppler = max( ...
        1, ...
        round(desiredTrainingVelocity_mps / velocityBinSize_mps));

    cfg.numGuardDoppler = max( ...
        1, ...
        round(desiredGuardVelocity_mps / velocityBinSize_mps));

    cfg.Pfa = 1e-4;
    cfg.minTrainingCells = 40;

    %% MTI clutter removal

    % Remove the slow-time mean from each fast-time sample
    iqMti = iq - mean(iq, 2);

    %% Hann windowing

    rangeWin = local_hann(params.Nfast);
    dopplerWin = local_hann(params.Nchirps).';

    iqWindowed = ...
        iqMti .* ...
        rangeWin .* ...
        dopplerWin;

    %% Range-Doppler processing

    rangeFFT = ...
        fft(iqWindowed, params.Nfast, 1);

    rdMap = ...
        fftshift( ...
            fft(rangeFFT, params.Nchirps, 2), ...
            2);

    % Retain positive FMCW range bins
    halfIdx = 1:floor(params.Nfast / 2);

    rdMapPositiveRange = rdMap(halfIdx, :);
    rdPower = abs(rdMapPositiveRange).^2;

    %% Range and radial-velocity axes

    beatFrequencyAxis = ...
        (halfIdx - 1) * ...
        params.fs / ...
        params.Nfast;

    rangeAxis = ...
        beatFrequencyAxis * ...
        params.c / ...
        (2 * params.S);

    dopplerFrequencyAxis = ...
        (-params.Nchirps/2 : params.Nchirps/2 - 1) * ...
        (params.PRF / params.Nchirps);

    velocityAxis = ...
        dopplerFrequencyAxis * ...
        params.lambda / 2;

    %% Edge-aware 2D CA-CFAR

    [detectionMask, ~, noiseMap] = ca_cfar_2d_edge( ...
        rdPower, ...
        cfg.numTrainRange, ...
        cfg.numTrainDoppler, ...
        cfg.numGuardRange, ...
        cfg.numGuardDoppler, ...
        cfg.Pfa, ...
        cfg.minTrainingCells);

    %% Suppress only the zero-range/DC bin

    detectionMask(1, :) = false;

    total_cfar_cells(fileIdx) = nnz(detectionMask);

    %% Group adjacent CFAR cells into clusters

    clusters = find_detection_clusters( ...
        detectionMask, ...
        rdPower, ...
        noiseMap, ...
        rangeAxis, ...
        velocityAxis);

    num_clusters(fileIdx) = numel(clusters);

    %% Handle scenarios with no CFAR cluster

    if isempty(clusters)

        fprintf( ...
            ['Scenario %03d | %-6s | NO DETECTION | ' ...
             'input SNR=%+6.2f dB | ' ...
             'truth R=%7.2f m, v=%+7.2f m/s\n'], ...
            scenario_id(fileIdx), ...
            char(actual_class(fileIdx)), ...
            input_snr_db(fileIdx), ...
            truth_range_m(fileIdx), ...
            truth_velocity_mps(fileIdx));

        continue;

    end

    %% Select the strongest detected cluster
    %
    % This selection uses only measured Range-Doppler power. It does not
    % use the simulated truth.

    clusterPeakPowers = [clusters.peakPower];

    [~, selectedClusterIdx] = max(clusterPeakPowers);

    target = clusters(selectedClusterIdx);

    detected(fileIdx) = true;

    %% Extract radar features

    estimated_range_m(fileIdx) = ...
        target.peakRange;

    estimated_velocity_mps(fileIdx) = ...
        target.peakVel;

    absolute_speed_mps(fileIdx) = ...
        abs(target.peakVel);

    peak_power_db(fileIdx) = ...
        10 * log10(target.peakPower + eps);

    estimated_snr_db(fileIdx) = ...
        target.estimatedSnrDb;

    cluster_cfar_cells(fileIdx) = ...
        target.numCells;

    %% Calculate truth-verification errors

    range_error_m(fileIdx) = ...
        estimated_range_m(fileIdx) - ...
        truth_range_m(fileIdx);

    velocity_error_mps(fileIdx) = ...
        estimated_velocity_mps(fileIdx) - ...
        truth_velocity_mps(fileIdx);

    %% Print one summary line per scenario

    fprintf( ...
        ['Scenario %03d | %-6s | DETECTED | ' ...
         'input SNR=%+6.2f dB | ' ...
         'truth R=%7.2f m, v=%+7.2f m/s | ' ...
         'est R=%7.2f m, v=%+7.2f m/s | ' ...
         'processed SNR=%6.2f dB\n'], ...
        scenario_id(fileIdx), ...
        char(actual_class(fileIdx)), ...
        input_snr_db(fileIdx), ...
        truth_range_m(fileIdx), ...
        truth_velocity_mps(fileIdx), ...
        estimated_range_m(fileIdx), ...
        estimated_velocity_mps(fileIdx), ...
        estimated_snr_db(fileIdx));

end

%% ------------------------------------------------------------------------
% Build feature table
% -------------------------------------------------------------------------

featureTable = table( ...
    scenario_id, ...
    actual_class, ...
    received_power_dbm, ...
    input_snr_db, ...
    rcs_m2, ...
    detected, ...
    estimated_range_m, ...
    estimated_velocity_mps, ...
    absolute_speed_mps, ...
    peak_power_db, ...
    estimated_snr_db, ...
    cluster_cfar_cells, ...
    total_cfar_cells, ...
    num_clusters, ...
    truth_range_m, ...
    truth_velocity_mps, ...
    range_error_m, ...
    velocity_error_mps);

featureTableFile = fullfile( ...
    outputDir, ...
    "step6d_physics_feature_table_round3.csv");

writetable(featureTable, featureTableFile);

%% ------------------------------------------------------------------------
% Print summary
% -------------------------------------------------------------------------

numDetected = nnz(detected);
detectionRate = 100 * numDetected / numScenarios;

fprintf("\n");
fprintf("Step 6D Results\n");
fprintf("------------------------------------------------------------\n");
fprintf("Detected scenarios: %d of %d (%.1f%%)\n", ...
    numDetected, ...
    numScenarios, ...
    detectionRate);

if numDetected > 0

    meanAbsoluteRangeError = mean( ...
        abs(range_error_m(detected)));

    meanAbsoluteVelocityError = mean( ...
        abs(velocity_error_mps(detected)));

    fprintf("Mean absolute range error:        %.3f m\n", ...
        meanAbsoluteRangeError);

    fprintf("Mean absolute velocity error:     %.3f m/s\n", ...
        meanAbsoluteVelocityError);

    fprintf("Lowest detected input SNR:       %+6.2f dB\n", ...
        min(input_snr_db(detected)));

end

targetClasses = unique(actual_class);

for classIdx = 1:numel(targetClasses)

    currentClass = targetClasses(classIdx);
    classMask = actual_class == currentClass;

    fprintf("%-6s detection rate: %5.1f%% (%d/%d)\n", ...
        char(currentClass), ...
        100 * nnz(detected(classMask)) / nnz(classMask), ...
        nnz(detected(classMask)), ...
        nnz(classMask));

end

fprintf("Saved feature table to:\n");
fprintf("  %s\n", featureTableFile);

%% ------------------------------------------------------------------------
% Plot 1: Actual versus estimated range and velocity
% -------------------------------------------------------------------------

validIdx = detected;

if any(validIdx)

    figure( ...
        "Color", ...
        "w", ...
        "Position", ...
        [100, 100, 1100, 500]);

    subplot(1, 2, 1);

    scatter( ...
        truth_range_m(validIdx), ...
        estimated_range_m(validIdx), ...
        65, ...
        input_snr_db(validIdx), ...
        "filled");

    hold on;
    grid on;
    box on;

    minRange = min([ ...
        truth_range_m(validIdx); ...
        estimated_range_m(validIdx)]);

    maxRange = max([ ...
        truth_range_m(validIdx); ...
        estimated_range_m(validIdx)]);

    plot( ...
        [minRange, maxRange], ...
        [minRange, maxRange], ...
        "k--", ...
        "LineWidth", ...
        1.5);

    xlabel("Actual range (m)");
    ylabel("Estimated range (m)");
    title("Actual vs Estimated Range");
    axis equal;
    xlim([minRange, maxRange]);
    ylim([minRange, maxRange]);

    subplot(1, 2, 2);

    scatter( ...
        truth_velocity_mps(validIdx), ...
        estimated_velocity_mps(validIdx), ...
        65, ...
        input_snr_db(validIdx), ...
        "filled");

    hold on;
    grid on;
    box on;

    minVelocity = min([ ...
        truth_velocity_mps(validIdx); ...
        estimated_velocity_mps(validIdx)]);

    maxVelocity = max([ ...
        truth_velocity_mps(validIdx); ...
        estimated_velocity_mps(validIdx)]);

    plot( ...
        [minVelocity, maxVelocity], ...
        [minVelocity, maxVelocity], ...
        "k--", ...
        "LineWidth", ...
        1.5);

    xlabel("Actual radial velocity (m/s)");
    ylabel("Estimated radial velocity (m/s)");
    title("Actual vs Estimated Velocity");
    axis equal;
    xlim([minVelocity, maxVelocity]);
    ylim([minVelocity, maxVelocity]);

    colorbar;

    comparisonFigureFile = fullfile( ...
        outputDir, ...
        "step6d_actual_vs_estimated_round3.png");

    exportgraphics( ...
        gcf, ...
        comparisonFigureFile, ...
        "Resolution", ...
        300);

    fprintf("Saved actual-versus-estimated plot to:\n");
    fprintf("  %s\n", comparisonFigureFile);

end

%% ------------------------------------------------------------------------
% Plot 2: Raw input SNR versus processed estimated SNR
% -------------------------------------------------------------------------

if any(detected)

    figure( ...
        "Color", ...
        "w", ...
        "Position", ...
        [100, 100, 850, 600]);

    hold on;
    grid on;
    box on;

    detectedClasses = unique(actual_class(detected));

    for classIdx = 1:numel(detectedClasses)

        currentClass = detectedClasses(classIdx);

        classMask = ...
            detected & ...
            actual_class == currentClass;

        scatter( ...
            input_snr_db(classMask), ...
            estimated_snr_db(classMask), ...
            75, ...
            "filled", ...
            "DisplayName", ...
            char(currentClass));

    end

    xline( ...
        0, ...
        "k--", ...
        "0 dB raw input SNR", ...
        "LineWidth", ...
        1.25);

    xlabel("Physics-Based Raw Input SNR (dB)");
    ylabel("Processed Peak-to-Local-Noise SNR (dB)");
    title("Step 6D: Input SNR vs Processed Detection SNR");

    legend("Location", "best");

    hold off;

    snrFigureFile = fullfile( ...
        outputDir, ...
        "step6d_input_vs_processed_snr_round3.png");

    exportgraphics( ...
        gcf, ...
        snrFigureFile, ...
        "Resolution", ...
        300);

    fprintf("Saved input-versus-processed-SNR plot to:\n");
    fprintf("  %s\n", snrFigureFile);

end

%% ------------------------------------------------------------------------
% Plot 3: Normalized extracted-feature heatmap
% -------------------------------------------------------------------------

featureMatrix = [ ...
    estimated_range_m, ...
    absolute_speed_mps, ...
    peak_power_db, ...
    estimated_snr_db, ...
    cluster_cfar_cells];

featureNames = [ ...
    "Range", ...
    "Abs Speed", ...
    "Peak Power", ...
    "Processed SNR", ...
    "CFAR Cells"];

validFeatureRows = ...
    detected & ...
    all(isfinite(featureMatrix), 2);

if any(validFeatureRows)

    validFeatureMatrix = ...
        featureMatrix(validFeatureRows, :);

    featureMean = mean( ...
        validFeatureMatrix, ...
        1);

    featureStandardDeviation = std( ...
        validFeatureMatrix, ...
        0, ...
        1);

    % Prevent division by zero if a feature never changes.
    featureStandardDeviation( ...
        featureStandardDeviation == 0) = 1;

    normalizedFeatures = ...
        (validFeatureMatrix - featureMean) ./ ...
        featureStandardDeviation;

    scenarioLabels = compose( ...
        "%03d %s", ...
        scenario_id(validFeatureRows), ...
        actual_class(validFeatureRows));

    figure( ...
        "Color", ...
        "w", ...
        "Position", ...
        [100, 100, 950, 650]);

    heatmapChart = heatmap( ...
        featureNames, ...
        scenarioLabels, ...
        normalizedFeatures);

    heatmapChart.Title = ...
        "Normalized Round 3 Radar Features";

    heatmapChart.XLabel = ...
        "Extracted Feature";

    heatmapChart.YLabel = ...
        "Scenario and Target Class";

    featureHeatmapFile = fullfile( ...
        outputDir, ...
        "step6d_feature_heatmap_round3.png");

    exportgraphics( ...
        gcf, ...
        featureHeatmapFile, ...
        "Resolution", ...
        300);

    fprintf("Saved feature heatmap to:\n");
    fprintf("  %s\n", featureHeatmapFile);

end

fprintf("\nStep 6D complete.\n");

%% ========================================================================
% Edge-aware 2D CA-CFAR
% ========================================================================

function [detectionMask, thresholdMap, noiseMap] = ...
    ca_cfar_2d_edge( ...
        powerMap, ...
        Tr, ...
        Td, ...
        Gr, ...
        Gd, ...
        Pfa, ...
        minTrainingCells)

    [numRangeBins, numDopplerBins] = size(powerMap);

    detectionMask = false( ...
        numRangeBins, ...
        numDopplerBins);

    thresholdMap = zeros( ...
        numRangeBins, ...
        numDopplerBins);

    noiseMap = nan( ...
        numRangeBins, ...
        numDopplerBins);

    for rangeIdx = 1:numRangeBins

        for dopplerIdx = 1:numDopplerBins

            rangeStart = max( ...
                1, ...
                rangeIdx - (Tr + Gr));

            rangeEnd = min( ...
                numRangeBins, ...
                rangeIdx + (Tr + Gr));

            dopplerStart = max( ...
                1, ...
                dopplerIdx - (Td + Gd));

            dopplerEnd = min( ...
                numDopplerBins, ...
                dopplerIdx + (Td + Gd));

            localWindow = powerMap( ...
                rangeStart:rangeEnd, ...
                dopplerStart:dopplerEnd);

            trainingMask = true(size(localWindow));

            guardRangeStart = max( ...
                1, ...
                rangeIdx - Gr - rangeStart + 1);

            guardRangeEnd = min( ...
                size(localWindow, 1), ...
                rangeIdx + Gr - rangeStart + 1);

            guardDopplerStart = max( ...
                1, ...
                dopplerIdx - Gd - dopplerStart + 1);

            guardDopplerEnd = min( ...
                size(localWindow, 2), ...
                dopplerIdx + Gd - dopplerStart + 1);

            % Remove the CUT and surrounding guard cells.
            trainingMask( ...
                guardRangeStart:guardRangeEnd, ...
                guardDopplerStart:guardDopplerEnd) = false;

            trainingCells = localWindow(trainingMask);

            numTrainingCells = numel(trainingCells);

            if numTrainingCells < minTrainingCells
                continue;
            end

            noiseEstimate = mean(trainingCells);

            alpha = numTrainingCells * ...
                (Pfa^(-1 / numTrainingCells) - 1);

            threshold = alpha * noiseEstimate;

            noiseMap(rangeIdx, dopplerIdx) = ...
                noiseEstimate;

            thresholdMap(rangeIdx, dopplerIdx) = ...
                threshold;

            if powerMap(rangeIdx, dopplerIdx) > threshold
                detectionMask(rangeIdx, dopplerIdx) = true;
            end

        end

    end

end

%% ========================================================================
% Connected-component clustering
% ========================================================================

function clusters = find_detection_clusters( ...
    mask, ...
    powerMap, ...
    noiseMap, ...
    rangeAxis, ...
    velocityAxis)

    [numRows, numCols] = size(mask);

    visited = false(numRows, numCols);

    clusters = struct( ...
        "numCells", {}, ...
        "peakPower", {}, ...
        "peakRange", {}, ...
        "peakVel", {}, ...
        "estimatedSnrDb", {});

    % Eight-neighbor connectivity
    neighborOffsets = [ ...
        -1, -1;
        -1,  0;
        -1,  1;
         0, -1;
         0,  1;
         1, -1;
         1,  0;
         1,  1];

    for rowIdx = 1:numRows

        for colIdx = 1:numCols

            if ~mask(rowIdx, colIdx) || ...
                    visited(rowIdx, colIdx)

                continue;

            end

            % Queue for breadth-first search
            queue = zeros(numRows * numCols, 2);

            queueStart = 1;
            queueEnd = 1;

            queue(queueEnd, :) = [rowIdx, colIdx];
            visited(rowIdx, colIdx) = true;

            clusterPixels = zeros( ...
                numRows * numCols, ...
                2);

            numClusterPixels = 0;

            while queueStart <= queueEnd

                currentPixel = queue(queueStart, :);
                queueStart = queueStart + 1;

                currentRow = currentPixel(1);
                currentCol = currentPixel(2);

                numClusterPixels = numClusterPixels + 1;

                clusterPixels( ...
                    numClusterPixels, :) = ...
                    [currentRow, currentCol];

                for neighborIdx = 1:size(neighborOffsets, 1)

                    neighborRow = ...
                        currentRow + ...
                        neighborOffsets(neighborIdx, 1);

                    neighborCol = ...
                        currentCol + ...
                        neighborOffsets(neighborIdx, 2);

                    if neighborRow < 1 || ...
                            neighborRow > numRows || ...
                            neighborCol < 1 || ...
                            neighborCol > numCols

                        continue;

                    end

                    if mask(neighborRow, neighborCol) && ...
                            ~visited(neighborRow, neighborCol)

                        queueEnd = queueEnd + 1;

                        queue(queueEnd, :) = [ ...
                            neighborRow, ...
                            neighborCol];

                        visited( ...
                            neighborRow, ...
                            neighborCol) = true;

                    end

                end

            end

            clusterPixels = clusterPixels( ...
                1:numClusterPixels, :);

            linearIndices = sub2ind( ...
                size(mask), ...
                clusterPixels(:, 1), ...
                clusterPixels(:, 2));

            clusterPowers = powerMap(linearIndices);

            [peakPower, localPeakIdx] = ...
                max(clusterPowers);

            peakRangeIdx = ...
                clusterPixels(localPeakIdx, 1);

            peakDopplerIdx = ...
                clusterPixels(localPeakIdx, 2);

            peakNoise = noiseMap( ...
                peakRangeIdx, ...
                peakDopplerIdx);

            estimatedSnrDb = 10 * log10( ...
                peakPower / max(peakNoise, eps));

            newCluster.numCells = ...
                numClusterPixels;

            newCluster.peakPower = ...
                peakPower;

            newCluster.peakRange = ...
                rangeAxis(peakRangeIdx);

            newCluster.peakVel = ...
                velocityAxis(peakDopplerIdx);

            newCluster.estimatedSnrDb = ...
                estimatedSnrDb;

            clusters(end + 1) = newCluster; 

        end

    end

end

%% ========================================================================
% Local Hann window
% ========================================================================

function window = local_hann(N)

    sampleIdx = (0:N-1).';

    window = ...
        0.5 - ...
        0.5 * cos( ...
            2 * pi * sampleIdx / (N - 1));

end
